name: Run rubocop
on: 
  pull_request:
    paths:
      - '**/*.rb'
      - '*.rb'
jobs:
  ci:
    runs-on: ubuntu-latest
    services:

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3800 # Optional, default value is 3306. The port of host
          container port: 3307 # Optional, default value is 3306. The port of container
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'ci_test' # Optional, default value is "test". The specified database which will be create
          mysql root password: ''
          mysql user: 'root'
          mysql password: ''

      - name: Create database and migrate tables
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate

      - name: Get bundle dependencies
        run: |
          bundle install

      - name: Run rubocop
        run: |
          bundle exec rubocop

      - name: Run minitest
        run: |
          bundle exec rake test
