name: Run rubocop
on: 
  pull_request:
    paths:
      - '**/*.rb'
      - '*.rb'
env:
  DATABASE_HOST: localhost
  DATABASE_NAME: ruby_on_moon_ci_test
  DATABASE_USER: root
  DATABASE_PASSWORD: ''
  DATABASE_ADAPTER: mysql2
  MYSQL_HOST: 127.0.0.1
  MYSQL_DB: github_actions_test
  MYSQL_USER: root
  MYSQL_ALLOW_EMPTY_PASSWORD: yes
  MYSQL_PASSWORD:
jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          DATABASE_HOST: localhost
          DATABASE_NAME: ruby_on_moon_ci_test
          DATABASE_USER: root
          DATABASE_PASSWORD: ''
          DATABASE_ADAPTER: mysql2
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: github_actions_test
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_PASSWORD:

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Create database and migrate tables
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate

      - name: Get bundle dependencies
        run: |
          bundle install

      - name: Run rubocop
        run: |
          bundle exec rubocop

      - name: Run minitest
        run: |
          bundle exec rake test
