name: Run rubocop

on:
  pull_request:
    types:
      - opened

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Get bundle dependencies
        run: |
          bundle install

      - name: Run rubocop
        run: |
          bundle exec rubocop
